### ISSUE TITLE
mockAxios V3

### ISSUE THREAD

**Issue by philippefutureboy** [kentcdodds/testing-workshop#101]
Hi 👋

I'd like to contribute the [following version of the mock for axios](https://gist.github.com/philippefutureboy/40559cc632613f6c5f12de48b6551662).

This version enables the `axios(config)` API, like so:

```
import axios from 'axios';

axios({
  method: 'post',
  url: '/user/12345',
  data: {
    firstName: 'Fred',
    lastName: 'Flintstone'
  }
});
```

Let me know if that interests you!

Have a great day ☀️

**Comment by kentcdodds** [comment]
That sure or not fully featured and would work well, but I prefer to keep the abstraction as simple as needed for the situation, so I don't think we'll make that change. Thanks anyway! Maybe you could make your code an open source package! (Though you may consider checking for existing packages that do the job first).

**Comment by philippefutureboy** [comment]
Great! Thanks for your answer :)
