### ISSUE TITLE
`npm run test:coverage` does not exist

### ISSUE THREAD

**Issue by mjlyons** [kentcdodds/testing-workshop#102]
Environment info:

* `node` version (`node --version`): v8.12.0
* `npm` version (`npm --version`): 6.4.1
* `yarn` version (`yarn --version`): 1.17.0

Problem description:

One of the steps in the troubleshooting section tells you to run `npm run test:coverage`, which does not exist. The closest that mentions coverage is `npm run test`.

Suggested solution:

If it's not used anymore, remove the line from README.md?

**Comment by kentcdodds** [comment]
Fixed. Thanks!
