### ISSUE TITLE
Test suite failed to run

### ISSUE THREAD

**Issue by dewaleolaoye** [kentcdodds/testing-workshop#113]
Environment info:

* `node` version (`10.16.3`):
* `npm` version (`6.9.0`):
* `yarn` version (`1.19.1`):

Problem description:

After cloning the repo, I `cd` into `testing-worshop` and run `npm run setup --silent`

I took *simple react test* exercise and run `npm run test:react` and got this error 

![Test failed](https://user-images.githubusercontent.com/44645460/70852601-a41ba880-1ea3-11ea-9bde-a4b8f293544d.PNG)

Suggested solution:

**Comment by rosen777** [comment]
I was getting the same issue with the expected suite failed to run for 'syntax-dynamic-import', the first time I ran `npm run setup --silent` as well.  The way in which I resolved is was to exit the test suite and run `npm run setup --silent` again. Hope this helps.

**Comment by ggofron** [comment]
Try to use older version of node with nvm, `8.9.4` should be fine. Remember it's an old workshop with many deprecated dependencies, you probably had some errors while installing and `syntax-dynamic-import` was not installed.
