### ISSUE TITLE
jest is not running after installation dependencies

### ISSUE THREAD

**Issue by usmanrehmat556** [kentcdodds/testing-workshop#118]
Environment info:

* `node` version (`node --12.13.1`):
* `npm` version (`npm --6.12.1`):
* `yarn` version (`yarn --1.22.0`):

Problem description:

<img width="837" alt="Screenshot 2020-04-20 at 7 42 26 PM" src="https://user-images.githubusercontent.com/35649024/79765334-e8cabb00-833f-11ea-816a-07aeb49f3f6b.png">

Suggested solution:

**Comment by kentcdodds** [comment]
I think this is probably an issue with watchman on your computer. Here's some docs on that: https://jestjs.io/docs/en/troubleshooting#watchman-issues

**Comment by dbertozzi** [comment]
I got the same error before I had watchman installed.
try: `brew install watchman`
