### ISSUE TITLE
Running the workshop using Docker

### ISSUE THREAD

**Issue by rodrigo398** [kentcdodds/testing-workshop#122]
Environment info:

* `node` version (`node --version`): v12.16.1
* `npm` version (`npm --version`): 6.14.4
* `yarn` version (`yarn --version`): 1.22.4

Problem description:

I'm coming from Frontmasters workshop and I'm just wanna know if there's any posibility to starting the project by setting up my enviroment using a docker image as a MongoDB instance, due to the fact that I can't install MongoDB in my laptop.

Thanks !.

**Comment by kentcdodds** [comment]
I imagine you could make it work, but I don't know how and can't support this project for it. Sorry.
