### ISSUE TITLE
Document how to setup a VM for cypress

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/testing-workshop#17]
I'd really like to have some sort of quick list of steps people could follow to set up a VM that has the project all ready to go and cypress installed. But I'm not very good at this kind of thing. Anyone wanna help with this? Vagrant seems like a good idea...

**Comment by kentcdodds** [comment]
Basically the VM should successfully be able to run through the project setup (meaning it needs all the requirements installed) and it should also be able to run `npm start e2e.dev` and launch cypress successfully.

**Comment by alayek** [comment]
@kentcdodds yes, vagrant is a great tool for this. I could probably put together a Vagrant file, with shell as provisioner and Virtual Box as provider. We would also need to configure shared directory, in the Vagrantfile.

Target host platform can be both Windows 8.1/10 and OSX el capitan or above.

Tell me your requirements, as in, what all are needed to be in the Vagrant guest; and I will give you a Vagrantfile with a script that provisions the system.

**Comment by kentcdodds** [comment]
Hi @alayek! Thanks for chiming in! So [here](https://github.com/kentcdodds/testing-workshop#system-requirements) are the system requirements. The only part of the workshop will be at the end when people on windows can't run `npm start e2e.dev` which launches the Cypress application (which does not yet support windows). So as long as it can launch Cypress then I think we're good. It honestly doesn't even need to share a folder with the host (could just clone the repo on the VM), but that would be super if that's not too challenging.

Let me know if you need any more info. Thanks so much!

**Comment by kentcdodds** [comment]
Ping @alayek :) If you have time... :)

**Comment by joelseq** [comment]
Hey @kentcdodds! Love this tutorial! I was wondering if you are still trying to do this? If you are then I was going to ask if it might be better to maybe create a docker image that has the project and everything set up and people can just run it that way?

**Comment by kentcdodds** [comment]
I don't think that we're going to do this. Especially considering that Cypress now supports windows! :tada:
