### ISSUE TITLE
nps e2e.run.cypress exited with code 0

### ISSUE THREAD

**Issue by mattferderer** [kentcdodds/testing-workshop#19]
Environment info:

- `mongo` version (`3.4.3`):
- `node` version (`6.10.2`):
- `npm` version (`3.10.10`):
- `yarn` version (`0.21.3`):

Problem description:
I was interested in checking out Cypress. I thought I would see if I could get this to run on Docker using Ubuntu 16. Therefore this is probably a very low priority issue. I ran into the following issue. I was wondering if this is an easy fix that someone could suggest a way around.

I did receive the following when I started the npm setup script:

```
🎉  Congrats! Your system is setup properly
You should be good to install and run things.
```

During the Cypress part though it got messy:

<details>

[api.test] [api.test.unit]
[api.test] [api.test.unit] Test Suites: 3 passed, 3 total
[api.test] [api.test.unit] Tests:       1 skipped, 18 passed, 19 total
[api.test] [api.test.unit] Snapshots:   0 total
[api.test] [api.test.unit] Time:        84.629s
[api.test] [api.test.unit] Ran all test suites.
[api.test] [api.test.unit] nps api.test.unit exited with code 0
[lint]
[lint] /projects/testing-workshop/api/src/models/__tests__/article.js
[lint]   42:6  warning  Unexpected disabled test  jest/no-disabled-tests
[lint]
[lint] ✖ 1 problem (0 errors, 1 warning)
[lint]
[lint] nps lint exited with code 0
[e2e] [build] [build.client] Compiled successfully.
[e2e] [build] [build.client]
[e2e] [build] [build.client] File sizes after gzip:
[e2e] [build] [build.client]
[e2e] [build] [build.client]   88.49 KB  build/static/js/main.3e7c3325.js
[e2e] [build] [build.client]
[e2e] [build] [build.client] The project was built assuming it is hosted at the server root.
[e2e] [build] [build.client] To override this, specify the homepage in your package.json.
[e2e] [build] [build.client] For example, add this to build it for GitHub Pages:
[e2e] [build] [build.client]
[e2e] [build] [build.client]   "homepage": "http://myname.github.io/myapp",
[e2e] [build] [build.client]
[e2e] [build] [build.client] The build folder is ready to be deployed.
[e2e] [build] [build.client] You may serve it with a static server:
[e2e] [build] [build.client]
[e2e] [build] [build.client]   yarn global add serve
[e2e] [build] [build.client]   serve -s build
[e2e] [build] [build.client]
[e2e] [build] [build.client] nps build.client exited with code 0
[e2e] [build] nps build exited with code 0
[e2e] [api] nps executing: node ./scripts/e2e-api
[e2e] [mongo] nps executing: node ./scripts/e2e-mongo
[e2e] [client] nps executing: node ./scripts/e2e-client
[e2e] [cypress] nps executing: node ./scripts/e2e-cypress
[e2e] [api] 🔑  starting api server: npm start  --silent
[e2e] [mongo] 🔑  starting mongodb: mongod --dbpath /projects/testing-workshop/.e2e/mongo-db --port 27018
[e2e] [client] 🔑  starting client server: npm start  --silent
[e2e] [cypress]
[e2e] [cypress] Cypress was not found: Installing a fresh copy.
[e2e] [cypress]
[e2e] [cypress]
[e2e] [cypress]
[e2e] [cypress]
[e2e] [cypress]   - Finished Installing /root/.cypress/Cypress (version: 0.19.1)
[e2e] [cypress] ☠  shutting down cypress
[e2e] [cypress] nps e2e.run.cypress exited with code 0
[e2e] --> Sending SIGTERM to other processes..
[e2e] [client] Terminated
[e2e] [client] nps e2e.run.client exited with code 143
[e2e] [mongo] nps e2e.run.mongo exited with code null
[e2e] [api] nps e2e.run.api exited with code null
[e2e] nps e2e exited with code 0

</details>

**Comment by kentcdodds** [comment]
Hmmm... Running cypress in Docker should work (and was [tried](https://github.com/kentcdodds/testing-workshop/pull/16)). Unfortunately, a big part of developing with cypress is the GUI application which you cannot run in Docker. :(

Feel free to continue discussion here, but supporting docker is not on the roadmap for this workshop I'm afraid.
