### ISSUE TITLE
Launch app without any articles and tags

### ISSUE THREAD

**Issue by fengcj** [kentcdodds/testing-workshop#27]
Environment info:

- `mongo` version (`mongod --version`):  v3.0.3
- `node` version (`node --version`): v7.6.0
- `npm` version (`npm --version`): 4.1.2
- `yarn` version (`yarn --version`): 0.22.0

Problem description:

 1) run `npm start dev` without any error
 2) launch `http://localhost:8080/#/` successfully, but the content of the website is as below:

![Image of Screen](https://github.com/fengcj/weewikipaint/blob/master/screen.png)
https://github.com/fengcj/weewikipaint/blob/master/screen.png

 3) check the response of `/api/articles?limit=10&offset=0`  as below:
          {"articles":[],"articlesCount":0} 
 

I guess this might be the DB issue.

@kentcdodds , please give me some suggestion.

**Comment by kentcdodds** [comment]
This is because you have a malformed JWT in your local storage. If you remove that it'll work fine.

We should probably fix the app so it removes it for you in that case. Would you like to do that? 😀

**Comment by fengcj** [comment]
@kentcdodds , thanks for quick reply. 
How can I remove my malformed JWT?

**Comment by kentcdodds** [comment]
Sorry, I'm on mobile, but Google how to access local storage for your browser in the dev tools.

**Comment by fengcj** [comment]
if you mean remove malformed JWT is clear local storage in the browser, I had done that, but still not working.
@kentcdodds , please feel free to do you own job first. I can wait when you have the time to solve this issue. Thank you again.

**Comment by kentcdodds** [comment]
I believe I've resolved the issue. You should be able to just do a git pull and get the updated (working hopefully?) app 👍

**Comment by fengcj** [comment]
@kentcdodds , now it works as expected. great job!

**Comment by wyattsweet** [comment]
@kentcdodds so far I'm loving the course! When I run `yarn start dev` my app is also loading without any articles or tags. In the dev tools there is nothing in Application > Local Storage to remove...I'm running
- Node v8.1.4
- mongo v3.4.6
- yarn 0.27.5

Any idea what might be going on?

**Comment by kentcdodds** [comment]
Could be that your `load-database` script failed. Try this:

```bash
node ./scripts/load-database
```

**Comment by wyattsweet** [comment]
The problem was I was trying to run this from my Dropbox folder. Once I moved it over to a different directory everything built perfectly. Thanks for the assistance @kentcdodds!

**Comment by kentcdodds** [comment]
Ah, yeah, putting npm-based projects in dropbox is probably not advisable considering how HUGE the node_modules directory can be 😅

**Comment by kentcdodds** [comment]
Glad you got it working!
