### ISSUE TITLE
Typo in 'other' file (Challenge 1)

### ISSUE THREAD

**Issue by bschwartz757** [kentcdodds/testing-workshop#30]
Environment info:

- `mongo` version (`mongod --version`):
- `node` version (`node --version`):
- `npm` version (`npm --version`):
- `yarn` version (`yarn --version`):

Problem description:

Hey there! I was going to submit a PR, but I had already cloned the repo and gone thru the setup and pushed to my own repo so... I didn't want to go through that setup again. The bug I found is really small so I'm just submitting it here.

Line 29 of `other/start.html`:
`// (because input1.value and input2.value will always be stirngs)`

Suggested solution:

should be:
`// (because input1.value and input2.value will always be strings)`

Thanks for the great course!

**Comment by kentcdodds** [comment]
Thanks!
