### ISSUE TITLE
Issue with ex 2 starting code

### ISSUE THREAD

**Issue by bschwartz757** [kentcdodds/testing-workshop#31]
Environment info:

- `mongo` version (`mongod --version`):
- `node` version (`node --version`):
- `npm` version (`npm --version`):
- `yarn` version (`yarn --version`):

Problem description:

Hey there! Also noticed that for ex. 2, the starting code I had for the test file (`__tests__/get-token-from-header.js`) was different than the video - it was mostly completed already (though I was able to add a little following the video.) A screenshot is attached showing what I started with there.

Suggested solution:

I'm not sure what's going on - I started with a fresh clone of the project repo and ran the setup steps and have been able to follow along so far. Maybe a past commit/PR to the repo got things out of whack? 

![screenshot from 2017-07-04 13-10-42](https://user-images.githubusercontent.com/7519644/27841974-5e4bb592-60ba-11e7-8363-a9f4d0def150.png)

**Comment by kentcdodds** [comment]
If you look in the repo, you'll see [this](https://github.com/kentcdodds/testing-workshop/blob/c121571f20d064320af55071ce793482c2c8f6ad/api/src/routes/utils/get-token-from-header.js): 

```javascript
export default getTokenFromHeader

// req is an express request object
// Here's an example:
// {
//   headers: {
//     authorization: 'Token blahblahblahblah.blahblahblah.blahblahblah',
//     // other headers
//   },
//   // other properties
// }
function getTokenFromHeader(req) {
  if (
    req.headers.authorization &&
    req.headers.authorization.split(' ')[0] === 'Token'
  ) {
    return req.headers.authorization.split(' ')[1]
  }
  return null
}
```

The problem is probably related to the fact that when the setup script runs, it actually copies the solutions everywhere and runs the tests to make sure that your setup is correct. Then it strips things back to the starting point. My guess is that you never got to that last step (something must have failed). Try running:

```
npm start split
```

That should fix everything up (though it will remove all of your current solutions...)

Good luck! And sorry about that.

**Comment by bschwartz757** [comment]
Hey Kent,

Thanks -  looks like that did indeed roll everything back, which is no
problem. I wasn't too far along and I'm probably better off doing the
exercises again anyway.

As far as the why, you're right - I did run into a snag when doing the
setup the first time around (specifically npm run setup --silent).
I just tried running the setup again from the forked/cloned version of your
repo, and it gets to a certain spot and then just hangs indefinitely which
is what it did before (see the screenshot attached.) I'm running on Ubuntu
16.04 at home and have all the major dependencies installed and working,
and I was able to run the app and tests just fine previously.

UPDATE: I just tried going through the setup again on my work computer
which is a Mac and it looks like the setup process actually succeeded on my
Linux machine as well - it just doesn't fully exit at the end (you may not
be able to see it in the screenshot due to my shell theme but it does say
nps split.e2e.verify exited with code 0 on the last line.) Since it never
exits I hit ctrl+c, thinking something was wrong, reset and then ran the
step-by-step install which is probably where things went wrong.

Also, rather than forking your repo to begin with I created my own in a
frontendmasters directory, cloned yours, and then switched the remote to
point at mine - so that may have caused the reset to not work as expected.
So I probably just shot myself in the foot there.

On the Mac, the setup succeeds and then exits as expected.

Thanks for your help, and sorry to bug you on a holiday!

- Blake Schwartz

**Comment by kentcdodds** [comment]
Sorry for the trouble! Glad you got it working. Thanks!
