### ISSUE TITLE
challenge 5: port conflict when attempting to run the tests against running app

### ISSUE THREAD

**Issue by bschwartz757** [kentcdodds/testing-workshop#34]
Environment info:

- `mongo` version (`mongod --version`):
- `node` version (`node --version`):
- `npm` version (`npm --version`):
- `yarn` version (`yarn --version`):

Problem description:

When the app is running (through `npm start dev`), if you try to run the integration tests the process end with `error: eaddrinuse: 3000`. 
Suggested solution:

I looked at the startServer() module and tried changing the port specified, as well as changing the port in `articles.test.js`: 
```
const api = axios.create({
  baseURL: 'http://localhost:3000/api',
})
```
but it didn't seem to help. When I run the mongo service only with `npm start mongo` the tests run fine against it.

**Comment by kentcdodds** [comment]
This will happen if you have the api server running in another terminal tab or if you have another service that's using port 3000. You need to stop the process running on port 3000. Sometimes it could be running in the background. Here's a bash function I use to kill a process taking up a port:

```
killport () 
{ 
    lsof -i tcp:"$@" | awk 'NR!=1 {print $2}' | xargs kill -9
}
```

I put that in my `.bash_profile` and then you can run:

```
killport 3000
```

And that will kill the process running on port 3000.

Good luck!

**Comment by bschwartz757** [comment]
awesome, thanks!! By the way, I sent an email to your github user email
address - wondering about server-side code coverage using Istanbul since I
noticed you were listed as a contributor there. In the testing workshop it
sounds like you're not sold on the cost/benefit of trying to implement this
but would appreciate any thoughts you might have.

Thanks again

- Blake Schwartz
