### ISSUE TITLE
Access to Mondodb data

### ISSUE THREAD

**Issue by pa87901** [kentcdodds/testing-workshop#35]
Environment info:

- `mongo` version (v3.4.2):
- `node` version (v7.8.0):
- `npm` version (v4.2.0):
- `yarn` version (v0.27.5):

Problem description:

I reached the Integration test exercise where we make api calls to the Mongo database for articles. I do not have access to the Mongo db data. How do I do this so that I can proceed with the integration test exercises?
I also tried the command I saw in another post to seed the data using the command **"node ./scripts/load-database"** to the db but got a problem connecting to Mongodb.
Thanks
<img width="1217" alt="screen shot 2017-08-11 at 5 16 38 pm" src="https://user-images.githubusercontent.com/22867659/29235947-f5e2d91e-7eb8-11e7-85fb-5c0acb52d303.png">

<img width="513" alt="screen shot 2017-08-11 at 4 59 30 pm" src="https://user-images.githubusercontent.com/22867659/29235726-8181d18a-7eb6-11e7-8769-88db3d6b41da.png">

<img width="1133" alt="screen shot 2017-08-11 at 4 50 21 pm" src="https://user-images.githubusercontent.com/22867659/29235662-7d0147ea-7eb5-11e7-9d42-ddee2c475357.png">

Suggested solution:

**Comment by vinnyA3** [comment]
I had a similar issue while fixing the avatar image bug.  When I first cloned the repo, I had no issues with the data whatsoever.  Unfortunately, I ran into problems after I purged my local repo.  Upon cloning and setting up the project the second time, I ran into mongo errors.  As a result, the database wasn't being populated with the generated data ( @kentcdodds  - any ideas as to why?  I killed all instances of mongod running / re-cloned the repo multiple times but still ran into mongo connection issues during setup ).

Here is what I did to fix the issue:

1.  Stop mongod: `sudo service mongod stop`
2.  Start mongo using the dev.mongo  script:  `yarn start dev.mongo`
3.  Now, with mongo running and waiting for a connection, manually populate the database using the generate script: `cd api && ./node_modules/.bin/babel-node scripts/generate`
4.  Start the api and client server:  `yarn start dev.api` , `yarn start dev.client`

I used tmux so I could run the dev scripts separately in the same terminal window.

**Comment by kentcdodds** [comment]
Thanks for putting this in here @vinnyA3!

I'm sorry that you all are having trouble with mongo. I really have no idea how to fix mongo related issues. I think in my effort to give you all a great "practical" experience, I may have gone a little overboard by requiring a database to be set up. In the future I think I'll just do JSON files 😅 

In any case, I'm afraid [I cannot help you](http://kcd.im/no-time) debug your mongo-related issues 😦 Best of luck to you.

**Comment by vinnyA3** [comment]
The workshop is great; your effort is greatly appreciated!  The mongo issue isn't really a big deal; it had me scratching my head for a bit, but I enjoyed the debugging process :smile:.  Thanks for the response @kentcdodds

**Comment by pa87901** [comment]
@kentcdodds Thank you for your response. I thought the workshop up to the integration tests was great and I am sure the rest afterwards would have been terrific too. At least I learnt a great deal about setting up the testing environment and unit/integration tests.

**Comment by kentcdodds** [comment]
Thanks. Now I know why I'm getting a lot of feedback on the first half of the workshop and very little on the second half: Many people can't get the second half to work 😨 😞
