### ISSUE TITLE
MemoryRouter is Misspelled

### ISSUE THREAD

**Issue by romarioraffington** [kentcdodds/testing-workshop#37]
https://github.com/kentcdodds/testing-workshop/blob/257a3c6bf920772eae236f736be9a8cbea44c75c/client/tests/integration/helpers/utils.js#L13

I can open a quick PR to fix this @kentcdodds, if that's cool with you 😃

**Comment by kentcdodds** [comment]
Hi @romarioraffington! Thank you! Sure, go ahead and open a PR for this! :) Nice catch :smile:
