### ISSUE TITLE
Issue installing/running on Windows 10

### ISSUE THREAD

**Issue by samiff** [kentcdodds/testing-workshop#39]
Problem description:
Install process cmd results: https://gist.github.com/samiff/ea037fe173405ae3e864a2bd824dd579
Following along from this [FEM video](https://frontendmasters.com/courses/testing-javascript/missing-avatar-bug).

I'm able to run `npm start dev` eventually and the site loads up, but no API data loads because the database has been created but empty. I'm a new developer used to dealing with scripts from a `package.json`, so I'm unsure where to troubleshoot from here.  Could the following be part of the problem?
```
generating and inserting data with `cd api && ./node_modules/.bin/babel-node scripts/generate`
'.' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by kentcdodds** [comment]
Hi @samiff!

If you could run all the scripts in Bash for Windows that would be best. If you can't do that for some reason, then try running this instead:

```
cd api && node_modules/.bin/babel-node scripts/generate
```

I think that should work...

Good luck!

**Comment by samiff** [comment]
Thanks Kent, got the database populated now by manually running those steps that failed with the ". is not recognized..." manually.

**Comment by kentcdodds** [comment]
Wonderful! I'm glad you got it to work!
