### ISSUE TITLE
Cypress.addParentCommand no longer works in Cypress 0.20.0 or above

### ISSUE THREAD

**Issue by dannypule** [kentcdodds/testing-workshop#40]
**Environment info:**
Cypress version: 0.20.3

**Problem description:**
package.json referenced an older version of Cypress but the version number included the "^" which meant that a later version was installed which contained a difference API for adding a command. I ran into an error when running the tests in Cypress.

**Suggested solution:**
In the following file '/testing-workshop/cypress/support/index.js' I fixed this by changing this line:

`Cypress.addParentCommand({visitApp})`

To this line:

`Cypress.Commands.add('visitApp', visitApp)`

Not sure if I should submit this as a pull request as it may or may not affect other people depending on what version they have installed. If this command was changed in the actual project whilst someone was using a pre-version-0.20 of Cypress they could run into issues.

**Comment by kentcdodds** [comment]
Thanks for letting me know. I'm going to be updating all dependencies eventually. I appreciate it.
