### ISSUE TITLE
scripts/load-database.js fails to load database on Windows.

### ISSUE THREAD

**Issue by idbartosz** [kentcdodds/testing-workshop#43]
Windows doesn't interpretate `./` and errors: `'.' is not recognized as an internal or external command, operable program or batch file.`
https://github.com/kentcdodds/testing-workshop/blob/65d17521c9f516529c6f749d64846b14743b0eaa/scripts/load-database.js#L44-L45

**Possible fix:**
Filter line 45 with `path.normalize` function. Code below is break down into 2 lines to prevent eslint `maximum line length of 80` error.
```
      const generateCommand = path.normalize(
        `cd api && ${babelNode} scripts/generate`)
```
Regards and yes I'm Windows user :trollface:

**Comment by kentcdodds** [comment]
Maybe that should be:

```javascript
 const babelNode = './node_modules/.bin/babel-node' 
 const generateCommand = `cd api && node ${babelNode} scripts/generate` 
```

Wanna see if that fixes it and make a PR?

**Comment by idbartosz** [comment]
Tested your solution and it doesn't solve the problem.

```
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by kentcdodds** [comment]
Huh, weird. Whelp, I'm going to be giving a second version of this workshop in a few months so I'll address these problems when I'm updating it for the second rendition. If you can figure out a solution that'd be super :)

**Comment by idbartosz** [comment]
I gave you a working solution in my first post but I leave PR to You :-)

**Comment by kentcdodds** [comment]
Ah! Sorry, I missed that. Thanks :)

**Comment by kentcdodds** [comment]
I'm rewriting the app so this is no longer an issue :) It's going to be much simpler :D
