### ISSUE TITLE
Old MongoDB path hardcoded on Windows

### ISSUE THREAD

**Issue by callummr** [kentcdodds/testing-workshop#5]
Environment info:

Windows 10, x64

- `mongo` version (`mongod --version`): 3.4.2
- `node` version (`node --version`): 7.4.0
- `npm` version (`npm --version`): 4.0.5
- `yarn` version (`yarn --version`): 0.20.3

Problem description:

- Ran `npm run setup`
- Received an error when it tried to verify my mongo installation:

```
The system cannot find the path specified.
there was an error determining your mongo version
{ Error: Command failed: "C:/Program Files/MongoDb/Server/3.2/bin/mongod.exe" --version
The system cannot find the path specified.
```

`verify.js` is looking for a hardcoded mongo path at line 74.

Suggested solution:

Not too sure, Windows is pretty tricky for stuff like this.

**Comment by kentcdodds** [comment]
Quick question for you, when you installed `mongo` did it add the `mongod` command to your PATH? By that I mean, can you just run `mongod` without having to explicitly reference the full path to the executable?

**Comment by callummr** [comment]
@kentcdodds I'd just checked that and sadly not, from a quick Google it doesn't attempt to and the only way to get it in your PATH is manually adding :(

**Comment by kentcdodds** [comment]
Do you think that I could reasonably have instructions for how to manually add it to your path if the command fails? Do you know of a good blogpost to teach people how to do that? I think that'd be the best way to do this.

**Comment by callummr** [comment]
I think it's fair to ask people to do that, and isn't too complex. As it varies by Windows version I'd suggest pointing people to something like [this tut](https://www.howtogeek.com/118594/how-to-edit-your-system-path-for-easy-command-line-access/), which covers Windows 7-10, and they can get the path to add by browsing to (...most likely) `C:\Program Files\MongoDB\Server\VERSION_NUMBER\bin`.

**Comment by kentcdodds** [comment]
That's perfect. Thanks!
