### ISSUE TITLE
Errors on Node v9.3

### ISSUE THREAD

**Issue by abinavseelan** [kentcdodds/testing-workshop#50]
## Environment info:

* `node` version (`node --version`): 9.3.0
* `npm` version (`npm --version`): 5.6.0
* `yarn` version (`yarn --version`): -

## Problem description:

This is related to https://github.com/kentcdodds/testing-workshop/issues/49. 🙂 

I'm getting this when I run `npm run setup --silent`

```bash
❯ npm run setup --silent
There is an issue with your system.
  - Your version of node (9.3.0) does not satisfy the desired range of ^8.4.0. Please install a version within the range. You can use http://git.io/nvm or https://github.com/coreybutler/nvm-windows to make changing your version of node easier.

If you don't care about these warnings, go ahead and install dependencies with `node ./scripts/install`
```

Also on a related note, The README says any node version 8.9.4 and npm version 5.6.0. However, `verify.js` still points to 8.4+ and 5.4.1+ respectively. Not sure if it's a biggie, but still a discrepancy between the the verifier and the README. 😄

**Comment by kentcdodds** [comment]
This is the perfect kind of feedback! Thank you! I'll decide what I want to do and fix it one way or another tomorrow. Thanks!

**Comment by fipo** [comment]
## Environment info:
* node version (node --version): 9.1.0
* npm version (npm --version): 5.6.0
* yarn version (yarn --version): 1.3.2

Problem description:
when I run `npm run setup --silent`
```
~/S/testing-workshop ❯❯❯ npm run setup --silent
There is an issue with your system.
  - Your version of node (9.1.0) does not satisfy the desired range of ^8.4.0. ...
```

@kentcdodds @abinavseelan same here ... 
I use `nvm` and I'm completely ok with install the nodejs 8.4. Btw current lts version is 8.9.3 ;)
