### ISSUE TITLE
[test:coverage] Unable to process function body node type: ArrowFunctionExpression

### ISSUE THREAD

**Issue by rigobauer** [kentcdodds/testing-workshop#53]
Environment info:

Tested in 2 systems:

Macbook Pro with 10.11.6 (El Capitan)
* `node` version (`node --version`): 8.9.4
* `npm` version (`npm --version`): 5.6.0
* `yarn` version (`yarn --version`): 1.3.2

PC HP Touchsmart 600 with Windows 10
* `node` version (`node --version`): 8.9.4
* `npm` version (`npm --version`): 5.6.0

Problem description:

When running `test:coverage, I get this messages:
[test:coverage] Unable to process function body node type: ArrowFunctionExpression
[test:coverage] Unable to process function body node type: ArrowFunctionExpression
.....................................

Test are apparently completed (test results show all tests passed)

Suggested solution:

Looks like it's related to this...
https://github.com/istanbuljs/istanbuljs/issues/119

**Comment by kentcdodds** [comment]
Yes, looks related. Luckily it doesn't break anything, so I think I'm going to go ahead and close this and hope that it's resolved in the other project. Thanks!
