### ISSUE TITLE
[npm run test:e2e:run]  CypressError: Timed out retrying: expected 'http://localhost:8001/login' to equal 'http://localhost:8001/'

### ISSUE THREAD

**Issue by rigobauer** [kentcdodds/testing-workshop#54]
Environment info:

Macbook Pro with 10.11.6 (El Capitan)
node version (node --version): 8.9.4
npm version (npm --version): 5.6.0
yarn version (yarn --version): 1.3.2

Also tested in a PC with Windows 10 without errors.

Problem description:

When I run `npm run test:e2e:run`, I get this error first and then some more. 

```
$ npm run test:e2e:run

> testing-workshop@2.0.0 pretest:e2e:run /Users/aiglesias/Coding/react/testing-workshop
> npm run build --silent

[server] src/auth.js -> dist/auth.js
[server] src/controllers/auth.js -> dist/controllers/auth.js
[server] src/controllers/posts.js -> dist/controllers/posts.js
[server] src/controllers/users.js -> dist/controllers/users.js
[server] src/db.js -> dist/db.js
[server] src/index.js -> dist/index.js
[server] src/routes/auth.js -> dist/routes/auth.js
[server] src/routes/index.js -> dist/routes/index.js
[server] src/routes/posts.js -> dist/routes/posts.js
[server] src/routes/users.js -> dist/routes/users.js
[server] src/start.js -> dist/start.js
[server] npm run build:server --silent exited with code 0
[client] Creating an optimized production build...
[client] Compiled successfully.
[client]
[client] File sizes after gzip:
[client]
[client]   71.01 KB  build/static/js/main.c199a80a.js
[client]   390 B     build/static/css/main.580cbb02.css
[client]
[client] The project was built assuming it is hosted at the server root.
[client] You can control this with the homepage field in your package.json.
[client] For example, add this to build it for GitHub Pages:
[client]
[client]   "homepage" : "http://myname.github.io/myapp",
[client]
[client] The build folder is ready to be deployed.
[client] You may serve it with a static server:
[client]
[client]   npm install -g serve
[client]   serve -s build
[client]
[client] Find out more about deployment here:
[client]
[client]   http://bit.ly/2vY88Kr
[client]
[client] Built the bundle with browser support for >1%, last 4 versions, Firefox ESR, not ie < 11.
[client] npm run build:client --silent exited with code 0

> testing-workshop@2.0.0 test:e2e:run /Users/aiglesias/Coding/react/testing-workshop
> as-a E2E npm-run-all --parallel --race start:core cy:run


> testing-workshop@2.0.0 cy:run /Users/aiglesias/Coding/react/testing-workshop
> cypress run


> testing-workshop@2.0.0 start:core /Users/aiglesias/Coding/react/testing-workshop
> concurrently --names "server,client" --prefix "[{name}]" --prefix-colors "bgCyan.reset.bold,bgGreen.reset.bold" "npm run start:server --silent" "npm run start:client --silent"

[client] serve: Running on port 8001
[server] Listening on port 3001

Started video recording: /Users/aiglesias/Coding/react/testing-workshop/cypress/videos/kjkln.mp4

  (Tests Starting)

  authentication
    ✓ should allow users to register (4715ms)
    1) should allow existing users to login

  authentication
    ✓ should allow existing users to login (7810ms)


  2 passing (28s)
  1 failing

  1) authentication should allow existing users to login:
     CypressError: Timed out retrying: expected 'http://localhost:8001/login' to equal 'http://localhost:8001/'
      at Object.cypressErr (http://localhost:8001/__cypress/runner/cypress_runner.js:65859:11)
      at Object.throwErr (http://localhost:8001/__cypress/runner/cypress_runner.js:65824:18)
      at Object.throwErrByPath (http://localhost:8001/__cypress/runner/cypress_runner.js:65851:17)
      at retry (http://localhost:8001/__cypress/runner/cypress_runner.js:59963:16)
      at http://localhost:8001/__cypress/runner/cypress_runner.js:52481:18
      at tryCatcher (http://localhost:8001/__cypress/runner/cypress_runner.js:6268:23)
      at Promise._settlePromiseFromHandler (http://localhost:8001/__cypress/runner/cypress_runner.js:4290:31)
      at Promise._settlePromise (http://localhost:8001/__cypress/runner/cypress_runner.js:4347:18)
      at Promise._settlePromise0 (http://localhost:8001/__cypress/runner/cypress_runner.js:4392:10)
      at Promise._settlePromises (http://localhost:8001/__cypress/runner/cypress_runner.js:4467:18)
      at Async._drainQueue (http://localhost:8001/__cypress/runner/cypress_runner.js:1200:16)
      at Async._drainQueues (http://localhost:8001/__cypress/runner/cypress_runner.js:1210:10)
      at Async.drainQueues (http://localhost:8001/__cypress/runner/cypress_runner.js:1084:14)


  (Tests Finished)

  - Tests:           3
  - Passes:          2
  - Failures:        1
  - Pending:         0
  - Duration:        28 seconds
  - Screenshots:     1
  - Video Recorded:  true
  - Cypress Version: 1.4.1


  (Screenshots)

  - /Users/aiglesias/Coding/react/testing-workshop/cypress/screenshots/authentication -- should allow existing users to login.png (1280x720)


  (Video)

  - Started processing:   Compressing to 32 CRF
  - Finished processing:  /Users/aiglesias/Coding/react/testing-workshop/cypress/videos/kjkln.mp4 (26 seconds)


  (All Done)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testing-workshop@2.0.0 cy:run: `cypress run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the testing-workshop@2.0.0 cy:run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aiglesias/.npm/_logs/2018-02-02T17_24_23_397Z-debug.log
[server] npm run start:server --silent exited with code null
[client] npm run start:client --silent exited with code null
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testing-workshop@2.0.0 start:core: `concurrently --names "server,client" --prefix "[{name}]" --prefix-colors "bgCyan.reset.bold,bgGreen.reset.bold" "npm run start:server --silent" "npm run start:client --silent"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the testing-workshop@2.0.0 start:core script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aiglesias/.npm/_logs/2018-02-02T17_24_23_738Z-debug.log
ERROR: "cy:run" exited with 1.
npm-run-all exit code 1
Error: npm-run-all exit code 1
    at ChildProcess.proc.on (/Users/aiglesias/Coding/react/testing-workshop/node_modules/as-a/src/run-command.js:38:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! testing-workshop@2.0.0 test:e2e:run: `as-a E2E npm-run-all --parallel --race start:core cy:run`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the testing-workshop@2.0.0 test:e2e:run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aiglesias/.npm/_logs/2018-02-02T17_24_23_841Z-debug.log
```

Suggested solution:

**Comment by kentcdodds** [comment]
Any chance you could share the video it recorded? It's at `/Users/aiglesias/Coding/react/testing-workshop/cypress/videos/kjkln.mp4`

**Comment by rigobauer** [comment]
Here you have it. Is the last try I did...

[wnpdd.mp4.zip](https://github.com/kentcdodds/testing-workshop/files/1690537/wnpdd.mp4.zip)

**Comment by kentcdodds** [comment]
Thanks for that. It's interesting. I'm not sure whether it's the video or something else, but it appears to me that it's going very slowly. More slowly than it does on my machine. Could you run `npm run test:e2e` and run the auth tests from the Cypress app? Maybe that'll give us some insight...

**Comment by rigobauer** [comment]
Sorry, not sure if I'm getting it. So you want me to execute first...

npm run test:e2e

... and after it finishes execute...

npm run cy:run

Is this correct?

**Comment by rigobauer** [comment]
OK... I get it... I'm running `npm run test:e2e` and I see the interface....

**Comment by rigobauer** [comment]
`npm run test:e2e` runs without errors...

![captura de pantalla 2018-02-02 a las 20 50 54](https://user-images.githubusercontent.com/29883162/35752075-e7dce284-085a-11e8-9e07-25931d111765.png)

$ npm run test:e2e

> testing-workshop@2.0.0 test:e2e /Users/aiglesias/Coding/react/testing-workshop
> as-a E2E npm-run-all --parallel --race dev:core cy:open


> testing-workshop@2.0.0 dev:core /Users/aiglesias/Coding/react/testing-workshop
> concurrently --names "server,client" --prefix "[{name}]" --prefix-colors "bgCyan.reset.bold,bgGreen.reset.bold" "npm run dev:server --silent" "npm run dev:client --silent"


> testing-workshop@2.0.0 cy:open /Users/aiglesias/Coding/react/testing-workshop
> cypress open

[server] Listening on port 3001
[client] Starting the development server...
[client]
[client] Compiled successfully!
[client]
[client] You can now view client in the browser.
[client]
[client]   Local:            http://localhost:8001/
[client]   On Your Network:  http://192.168.199.110:8001/
[client]
[client] Note that the development build is not optimized.
[client] To create a production build, use npm run build.
[client]
GET /__/ 200 68.897 ms - -
GET /__cypress/runner/cypress_runner.css 200 119.964 ms - -
GET /__cypress/runner/cypress_runner.js 200 695.984 ms - -
GET /__cypress/static/favicon.ico 200 17.442 ms - -
GET /__cypress/runner/fonts/fontawesome-webfont.woff2?v=4.7.0 200 8.337 ms - 77160
GET /__cypress/iframes/integration/auth.js 200 37.609 ms - 703
GET /__cypress/tests?p=cypress/support/index.js-395 200 13083.871 ms - -
GET /__cypress/tests?p=cypress/e2e/auth.js-378 200 14316.957 ms - -
GET /__/ 200 42.913 ms - -
GET /__cypress/runner/cypress_runner.css 200 122.790 ms - -
GET /__cypress/runner/cypress_runner.js 200 554.776 ms - -
GET /__cypress/static/favicon.ico 200 9.074 ms - -
GET /__cypress/runner/fonts/fontawesome-webfont.woff2?v=4.7.0 200 4.834 ms - 77160
GET /__cypress/iframes/integration/auth.js 200 20.609 ms - 703
GET /__cypress/tests?p=cypress/support/index.js-547 200 42.291 ms - -
GET /__cypress/tests?p=cypress/e2e/auth.js-524 200 180.682 ms - -
GET /?api-url=http%3A%2F%2Flocalhost%3A3001%2Fapi 200 12.541 ms - -
GET /static/js/bundle.js 200 339.479 ms - -
GET /static/media/twitter.18f6d382.svg 200 24.378 ms - -
GET /static/media/github.c16f044e.svg 200 27.867 ms - -
GET /api/users 200 62.802 ms - -
GET /api/posts 200 77.897 ms - -
GET /api/users 304 46.574 ms - -
GET /api/posts 304 16.809 ms - -
GET /sockjs-node/info?t=1517600900020 200 13.351 ms - -
OPTIONS /api/auth/register 204 15.226 ms - -
POST /api/auth/register 200 127.882 ms - -
OPTIONS /api/users 204 11.112 ms - -
OPTIONS /api/posts 204 5.519 ms - -
GET /api/posts 304 24.348 ms - -
GET /api/users 200 47.648 ms - -
GET /?api-url=http%3A%2F%2Flocalhost%3A3001%2Fapi 200 3.568 ms - -
GET /static/js/bundle.js 304 18.612 ms - -
GET /static/media/twitter.18f6d382.svg 304 5.480 ms - -
GET /static/media/github.c16f044e.svg 304 6.838 ms - -
GET /api/users 200 10.838 ms - -
GET /api/posts 304 7.854 ms - -
GET /api/users 304 7.732 ms - -
GET /api/posts 304 5.910 ms - -
GET /sockjs-node/info?t=1517600903377 200 12.267 ms - -
OPTIONS /api/auth/login 204 8.894 ms - -
POST /api/auth/login 200 22.005 ms - -
GET /api/users 304 9.508 ms - -
GET /api/posts 304 28.781 ms - -

**Comment by rigobauer** [comment]
Upps!! Wait!! When I close the Cypress Window I get this in the terminal...

```
[server] npm run dev:server --silent exited with code null
[client] events.js:183
[client]       throw er; // Unhandled 'error' event
[client]       ^
[client]
[client] Error: write EPIPE
[client]     at _errnoException (util.js:1022:11)
[client]     at WriteWrap.afterWrite [as oncomplete] (net.js:867:14)
[client] npm run dev:client --silent exited with code null
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testing-workshop@2.0.0 dev:core: `concurrently --names "server,client" --prefix "[{name}]" --prefix-colors "bgCyan.reset.bold,bgGreen.reset.bold" "npm run dev:server --silent" "npm run dev:client --silent"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the testing-workshop@2.0.0 dev:core script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aiglesias/.npm/_logs/2018-02-02T19_54_58_067Z-debug.log
```

**Comment by kentcdodds** [comment]
Yeah, that's fine. Weird that it doesn't work when running headlessly (with `npm run test:e2e:run`) 🤔 

Mind doing a little more digging to see what's up?

**Comment by rigobauer** [comment]
Sure, man!! But now I have to leave (it's 9:35PM here now and kids are back home, so the real work is here!! XD)

Just tell me what you need me to do and I'll do it tomorrow morning as soon as I wake up!

**Comment by rigobauer** [comment]
Mmm... look at this...

https://github.com/coryhouse/react-slingshot/issues/449

... could be related? The watchman dependency?

**Comment by kentcdodds** [comment]
Interesting. No that's probably not it. These are the cypress tests that are failing. I don't think cypress depends on watchman. Hmm...

We just need to figure out why the browser isn't being redirected from the login page to home in that particular test. Weird that we can only reproduce on your machine and only in headless mode... Hmmm...

**Comment by rigobauer** [comment]
No, as you supposed, it didn't work... :(

Mmmm... it looks to me that there's two different problems:

- The test timeout (redirection failure). Only in headless mode.

- The final error when the test finish. Happens in both execution modes.

Just to eliminate the posibility that there's been somo problem with the installation...
1. Doing an `npm clean cache` and reinstalling dependencies?
2. Going hardcore... remove the directory and clone it again?

The only problem I see with this is that if it solve it, we'll never know what's actually happening and if it could happen again...

**Comment by kentcdodds** [comment]
I wouldn't worry about it. If you can fix it by doing a fresh clone then I say let's just let it be that way :) Unless we see other people experience this I don't think there's much point. So why don't you give that a try.

**Comment by rigobauer** [comment]
This is super "funny"...

1. Fresh clone, execute `npm run setup --silent` and.... everything works without problems! No errors.

2. After that I've executed `npm run test:e2e:run` and the timeout problem isn't there but at the end I keep getting one of the ELIFECYCLE errors...

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testing-workshop@2.0.0 start:core: `concurrently --names "server,client" --prefix "[{name}]" --prefix-colors "bgCyan.reset.bold,bgGreen.reset.bold" "npm run start:server --silent" "npm run start:client --silent"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the testing-workshop@2.0.0 start:core script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aiglesias/.npm/_logs/2018-02-02T21_22_32_226Z-debug.log

Anyway, it makes sense comparing with the `npm run test:e2e`... In both case I get an error when I end the test.

3. BUT... I tried once again `npm run test:e2e:run`... And now I have all the errors again (timeout included). So... you're application hates me!! XD

Now I really have to leave. I'll continue tomorrow with a "refreshed" mind!

**Comment by kentcdodds** [comment]
Ignore the npm errors. Those are just telling you that a script you ran with npm had a problem. Look above in the rest of the output and you'll see the real problem.

**Comment by rigobauer** [comment]
Interesting... I've been digging a little bit more. After having a look at the code, it seems that obviously the problem (timeout) is being triggered in this test of auth.js...

```js
  it('should allow existing users to login', () => {
    createNewUser().then(user => {
      cy
        .visitApp()
        .getByTestId('login-link')
        .click()
        .getByTestId('username-input')
        .type(user.username)
        .getByTestId('password-input')
        .type(user.password)
        .getByTestId('login-submit')
        .click()
      assertRoute('/')
      cy.getByTestId('username-display').should('contain', user.username)
    })
  })
```

Attending at the error message, it looks like it timeouts trying to execute the `assertRoute('/')` line. So, just to see if it changes anything, I've commented that line and run `npm run test:e2e:run` again, and is curious...

1. I run it once, and it WORKED!! No timeout error.

2. But then, I run it again, and then I got the timeout, but with a different message...

```js
1) authentication should allow existing users to login:
     CypressError: Timed out retrying: Expected to find element: '[data-test="username-display"]', but never found it.
      at Object.cypressErr (http://localhost:8001/__cypress/runner/cypress_runner.js:65859:11)
      at Object.throwErr (http://localhost:8001/__cypress/runner/cypress_runner.js:65824:18)
      at Object.throwErrByPath (http://localhost:8001/__cypress/runner/cypress_runner.js:65851:17)
      at retry (http://localhost:8001/__cypress/runner/cypress_runner.js:59963:16)
      at http://localhost:8001/__cypress/runner/cypress_runner.js:52481:18
      at tryCatcher (http://localhost:8001/__cypress/runner/cypress_runner.js:6268:23)
      at Promise._settlePromiseFromHandler (http://localhost:8001/__cypress/runner/cypress_runner.js:4290:31)
      at Promise._settlePromise (http://localhost:8001/__cypress/runner/cypress_runner.js:4347:18)
      at Promise._settlePromise0 (http://localhost:8001/__cypress/runner/cypress_runner.js:4392:10)
      at Promise._settlePromises (http://localhost:8001/__cypress/runner/cypress_runner.js:4467:18)
      at Async._drainQueue (http://localhost:8001/__cypress/runner/cypress_runner.js:1200:16)
      at Async._drainQueues (http://localhost:8001/__cypress/runner/cypress_runner.js:1210:10)
      at Async.drainQueues (http://localhost:8001/__cypress/runner/cypress_runner.js:1084:14)
```
    ... that looks like is caused by the next line after the commented one....

```js
cy.getByTestId('username-display').should('contain', user.username)
```

So, I'm thinking that looks like after I'm able to complete the logging test once, maybe something is not being ended or released correctly and the next executions is avoiding the cy chain to complete. I'm just guessing, of course...

**Comment by kentcdodds** [comment]
The way Cypress works is that it queues up your commands on the `cy` object. When it hits a command in the queue, it'll wait until the app reaches that state and if it never reaches that state after 4 seconds then it times out.

So the bug is: after the user submits the login form, they are not redirected to the home screen. So we need to figure out why that's not happening.

**Comment by kentcdodds** [comment]
Things have changed significantly so I think we're good now :+1:

**Comment by rigobauer** [comment]
I totally get it, Kent... I'm really sorry for dissapearing, but I've been in a few selection process and this is harder and more exhausting than taking that freaking ring to Mordor...
