### ISSUE TITLE
Question - Integration testing performance/scalability

### ISSUE THREAD

**Issue by rovansteen** [kentcdodds/testing-workshop#55]
First of all, this is not a bug report or anything so feel free to close this if you want to keep this only for bug reports. Second, thanks for sharing this code here, there is a lot to learn from this on how to setup testing on different levels.

Now my question is, how 'scalable' is the integration testing setup with Jest? I had a similar setup with a medium sized application and started running in to performance issues quite soon. Because Jest compiles every test on it's own and you include the complete application from inside the test file it means that, let's say you have 20 different pages/views in your application, each with their own integration test file your application gets compiled 20 times when you run your tests. This made my tests slow and unusable and was only getting worse with each line of code I added. 

Do you have any ideas or recommendations about how to scale the integration tests when your application grows? I can only find trivial examples of a setup like this so I'm curious if someone tackled this for medium/large sized applications.

**Comment by kentcdodds** [comment]
Hey @rovansteen!

So we're doing things this way at PayPal and it's working out well for us. The biggest problem is finding a way for the server to start up quickly. But that's something we want anyway, so I don't feel bad feeling pressure in that way. One thing that we could do that I haven't tried is starting up the server before all the tests and reusing that same server for all the integration tests.

> Because Jest compiles every test on it's own and you include the complete application from inside the test file 

I'm not sure that's a correct assumption. I'm assuming that by compilation you're referring to babel or TypeScript. I'm pretty sure that Jest doesn't wastefully transpile files for every single test but aggressively caches compiled versions of files.

I have seen what you're talking about before when I had a memory leak in my code. I'm guessing that's probably what you're seeing.
