### ISSUE TITLE
Changing axios instance defaults after its created seem buggy

### ISSUE THREAD

**Issue by hontas** [kentcdodds/testing-workshop#60]
seem to alter other instances as well
```js
const authApi = axios.create({
    baseURL
});
authApi.defaults.headers.common.Authorization = `Bearer ${registeredUser.token}`;
```

works
```js
const authApi = axios.create({
    baseURL,
    headers: {Authorization: `Bearer ${registeredUser.token}`}
});
```

**Comment by kentcdodds** [comment]
Thanks @hontas!

**Comment by kentcdodds** [comment]
Done!

Thanks!

**Comment by hontas** [comment]
No probs, thanks again for the workshop! And as a sitenote, the root cause for this issue may soon be resolved! Seems the bug in axios has been there for auite some time. https://github.com/axios/axios/pull/1391

**Comment by kentcdodds** [comment]
Oh nice! That's awesome!
