### ISSUE TITLE
Cypress.addParentCommand depecrated. Multiple other issues with running the Cypress tests.

### ISSUE THREAD

**Issue by ryarasi** [kentcdodds/testing-workshop#75]
Environment info:

Running on Ubuntu 16.04 

* `node` version (`node --version`): v8.11.1
* `npm` version (`npm --version`): 5.6.0
* `yarn` version (`yarn --version`): 1.6.0

Problem description:

I'm enrolled in the **Testing Javascript Applications (ft. React and Redux)** course on FEM. 

I'm currently trying to follow along with the videos on end-to-end testing. I am on Ubuntu 16.04 and was able to get Cypress to install and work. But when I click on 'run all tests', it waits a while and outputs this error:-

````
Uncaught CypressError: Cypress.addParentCommand(...) has been removed and replaced by:

Cypress.Commands.add(...)

Instead of indicating 'parent', 'child', or 'dual' commands, you pass an options object
to describe the requirements around the previous subject. You can also enforce specific
subject types such as requiring the subject to be a DOM element.

To rewrite this custom command you'd likely write:

Cypress.Commands.add('[object Object]', function(){...})

https://on.cypress.io/custom-command-interface-changed

This error originated from your test code, not from Cypress.

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.

Check your console for the stack trace or click this message to see where it originated from.
```

Suggested solution:

I tried to follow along the error and update stuff, but it results in other errors that are difficult to interpret as a beginner, so I couldn't try to diagnose further.

I think Cypress has updated its API or something and the code in this app needs to be updated to reflect their changes. Kindly do so.

<!-- ideas are welcome! -->

**Comment by kentcdodds** [comment]
Hi! I'd recommend not watching that course. Watch [the updated one](https://frontendmasters.com/courses/testing-react/) instead.

**Comment by ryarasi** [comment]
Thanks Kent, if you don't recommend watching it, I would like to suggest that you guys archive that course, since it could mislead others into taking it first since it seems more generic than the updated one and so might seem like it's better to do it first. Just a suggestion.

Thanks :)
