### ISSUE TITLE
Incorrect 'fem' branch file tree

### ISSUE THREAD

**Issue by toddmacintyre** [kentcdodds/testing-workshop#76]
Problem description:

fem branch does not have file tree structure as shown in FEM workshop videos.

Suggested solution:

Either update fem branch to correct file tree structure, or eliminate suggestion in README.md for FEM users to use the 'fem' branch instead of 'master'.

**Comment by kentcdodds** [comment]
Sorry, it's a little confusing, but the 2017 workshop is not the same as the one that you're watching I think. I've adjusted the wording to make this more clear. Thanks!
