### ISSUE TITLE
Failed test after running client editor test

### ISSUE THREAD

**Issue by huchenme** [kentcdodds/testing-workshop#79]
Seem this error after running `npm run test:client`

```
 FAIL   client  client/src/screens/__tests__/editor.todo.js
  ● Test suite failed to run

    Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it islikely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel. (While processing preset: "/Users/huchenme/playground/testing-workshop/client/node_modules/babel-preset-react-app/index.js")
```

It is working if I downgrade `react-scripts` to version1

**Comment by kentcdodds** [comment]
Hi @huchenme, thank you for the issue! I'm not able to reproduce it however :-/

If you figure out anything else about this or discover a way to reproduce it and have a suggested fix, then please comment here and we can work it out. Thanks!

**Comment by wk32** [comment]
Hi Kent, 
I have the same problem too. To solve it, I included the following to the dev dependencies in package.json in /server and /client to make it work:
"@babel/core": "7.0.0-beta.46",
"babel-core": "7.0.0-bridge.0",

**Comment by wk32** [comment]
Hi @kentcdodds,

I had the same problem too. I fixed it after installing a devDependency in client/package.json:

````
babel-preset-react-app: "^3.1.2"
````

**Comment by kentcdodds** [comment]
Is this something that you see happens when you're in the `fem-2018` branch? Or the `master` branch? Or both?

**Comment by wk32** [comment]
it's on both` fem-2018` and `master branch `

**Comment by kentcdodds** [comment]
Ok, thanks. Would you like to make a PR for each branch to fix this?

**Comment by wk32** [comment]
Sure! I will post the PR soon.
