### ISSUE TITLE
Not able to push into my own repo

### ISSUE THREAD

**Issue by kushalmahajan** [kentcdodds/testing-workshop#96]
I'm trying to commit on my local machine after changing remote to one of my own repo and I'm not able to do. Error is `Git: husky > npm run -s precommit (node v10.14.1)` when I commit.
Using Node - 10.14.1

**Comment by kentcdodds** [comment]
Update the `package.json` and remove the `precommit` script.

**Comment by kushalmahajan** [comment]
Ok. Done and working
