### ISSUE TITLE
Feedback links stop working

### ISSUE THREAD

**Issue by ultrox** [kentcdodds/testing-workshop#97]
I'm going thruge your frontend masters testing workshop and trying to play along and fill the feedback.
http://ws.kcd.im/?ws=Testing&e=login.step-2%20(react-testing-library)&em=

which for some reason stop working. Step 1 as well.

**Comment by kentcdodds** [comment]
Whoops! Thanks for letting me know. I'll work that out.

**Comment by kentcdodds** [comment]
This has been fixed. Thanks!
